feat: customizable dependencies
ikke-t/podman-container-systemd pull request #41
Opened 2021-08-08 07:01 UTC by Yajo

This way we can sort the way containers should boot.

2021-08-15 10:47 UTC, ikke-t requested changes
Nice. Small beauty thing, I'd like to see the existing After=network.target as a default value, instead of hard coding it in the service file. I mean, if they are cusotmizeable, why not all while at it?

2021-08-15 10:48 UTC, ikke-t commented
Sorry it took time for me to answer, I was away on vacation without the laptop. I could merge this as is, but it would be nice if you could still add the minor thing I mentioned, and rebase.

2021-08-17 18:24 UTC, Yajo commented
Attended 😄

2021-08-18 11:50 UTC, ikke-t approved these changes
great, thanks!

2021-08-18 11:50 UTC, merged

2021-08-18 17:15 UTC, Yajo commented
Would you mind doing a release with all these changes?

2021-08-18 18:39 UTC, ikke-t commented
sure, no probs. 2.2.0 done.